[default]
src = 'contracts'
remappings = [
  'ds-test/=lib/ds-test/src/',
  'forge-std/=lib/forge-std/src/',
  'interfaces/=interfaces/',
  'deps/=deps/',
]
eth-rpc-url = "https://rpc.fantom.network"
